fakeannounce:
    automaticforsilentjoin: false
    join: '%p joined the game.'
    quit: '%p left the game.'
hooks:
    essentials: false
    luckperms: true
checkupdates: true
permissionsupdates:
    checkonworldchange: false
effects:
    lightning:
        count: 30
colornametags: true

permtest: false
debug: false
configVersionDoNotTouch: 
    SeriouslyThisWillEraseYourConfig: 5